# Generated by Django 5.2.8 on 2025-11-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_siembra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('etapa', models.CharField(max_length=100)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='lotes.lote')),
            ],
        ),
    ]
