# Generated by Django 5.2.8 on 2025-11-26 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('conductor', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('hora_llegada_estimada', models.DateTimeField()),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='transporte.transporte')),
            ],
        ),
    ]
